### PR TITLE
Enable extensions even for Schemas that use ref

### PR DESCRIPTION
**Pull request by raghuraman1**
Hi @frantuma ,

I would request this PR to enable passing on the swagger extensions even when the Schema uses ref.
I am trying to show using swagger extensions validation constraints that swagger or springdoc might not be showing. This includes even custom constraints. I am trying to leverage swagger extensions for this purpose.
The issue is properties of Complex Types use ref and such schemas currently don't allow anything other than $ref. The extensions in no way affect the type being referred.
I have provided a fix by this PR.

Raghu

### CODE REVIEW

**Comment by raghuraman1** [comment]
@frantuma 
**There will also be needed a subsequent ui change in the reactjs code.**
Meanwhile I have simplified the code changes.
I have 4 variations of the sample code just to demonstrate robustness of the code change.

**Variation 1**- https://github.com/teq-niq/sample/tree/extension-variation1
image
json:
[api-docs.json-variation1.txt](https://github.com/swagger-api/swagger-core/files/4549510/api-docs.json-variation1.txt)
image
[api-docs.yaml-variation1.txt](https://github.com/swagger-api/swagger-core/files/4549517/api-docs.yaml-variation1.txt)
image

**Variation 2**- https://github.com/teq-niq/sample/tree/extension-variation2
image
json:
[api-docs.json-variation2.txt](https://github.com/swagger-api/swagger-core/files/4549535/api-docs.json-variation2.txt)
image
yaml:
[api-docs.yaml-variation2.txt](https://github.com/swagger-api/swagger-core/files/4549540/api-docs.yaml-variation2.txt)
image

**Variation 3**- https://github.com/teq-niq/sample/tree/extension-variation3
image
json:
[api-docs.json-variation3.txt](https://github.com/swagger-api/swagger-core/files/4549560/api-docs.json-variation3.txt)
image
image

yaml:
[api-docs.yaml-variation3.txt](https://github.com/swagger-api/swagger-core/files/4549568/api-docs.yaml-variation3.txt)
image
image


**Variation 4**- https://github.com/teq-niq/sample/tree/extension-variation4
image
json:
[api-docs.json-variation4.txt](https://github.com/swagger-api/swagger-core/files/4549584/api-docs.json-variation4.txt)
image
image

yaml:
[api-docs.yaml-variation4.txt](https://github.com/swagger-api/swagger-core/files/4549589/api-docs.yaml-variation4.txt)
image
image

**Comment by raghuraman1** [comment]
Hi @frantuma,
I have simplified this as much as I could. I dont have any more code changes  in this unless you suggest. Hope you will review and merge.
Thanks.
Raghu

**Comment by raghuraman1** [comment]
Hi @frantuma 
It appears there has been no activity in swagger-core since April 16.
Hope you are fine and all is well.
R

**Comment by raghuraman1** [comment]
Hello @frantuma ,
Can you please look at this PR.
Thank you.
R

**Comment by lordpixel23** [comment]
This would be very useful. Currently extensions work in some cases but not others. If the $ref resolves to a primitive type like 'string' then the sibling 'x-foo' values are honored. But seem to get dropped entirely any time a $ref to an 'object' type is referenced. 

That is:
```
foo:
   $ref: #/bar
   x-foo: honored
bar:
   type: string
baz:
   #ref: #/bat
   x-foo: not honored
bat:
   type: object
```

The current behavior feels very inconsistent. Dumping the 'Schema' objects shows the extensions are missing if the type is 'Schema' but not if it is 'StringSchema' for example.

**Comment by jiawq** [comment]
I encountered the same problem, I hope the author can merge this code

**Comment by alishtory** [comment]
Mark

**Comment by raghuraman1** [comment]
Found 2 other ways to achieve this.
Will raise a new PR accordingly when ready if needed.

**Comment by T3rm1** [comment]
> This would be very useful. Although $ref isn't supposed to have siblings without an explicit allOf, it is massively useful and commonly used.

@lordpixel23 
Do you have a source for that? I checked both JSON Schema Core RFC and OpenAPI 3.0 specification and couldn't find such a limitation

@raghuraman1 
Why did you close this PR? I'd argue that it's a bug that extensions are not copied and it should be fixed.

**Comment by raghuraman1** [comment]
@T3rm1 I closed because there was no progress and I found some other way- but that aother way also showed no action

**Comment by T3rm1** [comment]
I'll create a new issue.

**Comment by raghuraman1** [comment]
Maybe we can just request the repository owners.  Just to try avoiding duplication. That said if you do create a new request link them and I will see if I need to refresh the code in the PR

**Pull request closed without merging**
