### PR TITLE
Bugfix for 867 (incorrect parsing of generic class when generic parameter is inner class)

### PR DESCRIPTION
**Pull request by cppexpert**
Bigfix for https://github.com/swagger-api/swagger-core/issues/867

### CODE REVIEW

**Comment by cppexpert** [comment]
Guys (@webron @fehguy), would it possible to merge it and push update to Maven Repo ? Thanks!

**Comment by webron** [comment]
Can you resend it against the develop_scala-2.10 branch?

**Comment by cppexpert** [comment]
Yes. Actually I just realized the fix is incomplete. Maybe you could help me. Here is how my new json listing looks like after this commit

```json
"RolesResponse": {
            "id": "RolesResponse",
            "description": "Paginated response",
            "required": [
                "items",
                "startIndex",
                "maxSize"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "description": "list of items",
                    "items": {
                        "$ref": "TimesheetProjectTaskRolesService.RoleRecord"
                    }
                },
                "startIndex": {
                    "type": "integer",
                    "format": "int32",
                    "description": "starting position of given items in complete list"
                },
                "maxSize": {
                    "type": "integer",
                    "format": "int32",
                    "description": "maximum number of items in complete list"
                }
            }
        }
```

The problem is that `TimesheetProjectTaskRolesService.RoleRecord` is not in list of models. What class is responsible for initial scan of classes and why this one might be skipped ?

**Comment by webron** [comment]
That's for @fehguy.

**Comment by cppexpert** [comment]
Closed this pull request as incomplete fix.

**Pull request closed without merging**
