### PR TITLE
CDI 2.0 beans.xml for swagger-jaxrs2 integration auto-discovery

### LINKED ISSUE #2617: Enable CDI w/ swagger-jaxrs2 & swagger-jersey2-jaxrs
Adding a beans.xml with `bean-discovery-mode="annotated"` might be enough for these jars to support CDI environments that register all discoverable `@Path` & `@Provider` classes!

### PR DESCRIPTION
**Pull request by derekm**
This tiny beans.xml file allows me to directly use Swagger 2.0's `swagger-jaxrs2` jar in CDI-enabled environments that auto-detect all `@Path` & `@Provider` annotated classes by merely declaring the following dependencies:
```
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.9.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
    </dependency>
```

BOOM! Live Swagger-2.0-provided `/openapi*` endpoints that are reflecting my other JAX-RS endpoints! I don't even need Swagger 2.0's convenient config file!

Fixes #2617

### CODE REVIEW

**Comment by derekm** [comment]
Yes, I could add a unit test... The unit test would need to use Weld or Arquillian. I'll see about coming up with something ASAP. Thanks!

**Comment by derekm** [comment]
@pjfanning -- I've added tests that use a portable CDI Extension to watch for `@Path` and `@Provider` annotations during CDI container lifecycle events. The tests interrogate this extension to check what classes were registered by the CDI container, confirming that the desired classes have been discovered.

**Comment by bcluap** [comment]
Since this change I am getting a NPE in TomEE when retrieving openapi.json:

java.lang.NullPointerException
	at org.apache.openejb.core.ivm.naming.MapObjectReference.getObject(MapObjectReference.java:34)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:183)
	at org.apache.openejb.core.ivm.ContextHandler.lookup(ContextHandler.java:58)
	at org.apache.openejb.cdi.CdiResourceInjectionService.lookup(CdiResourceInjectionService.java:200)
	at org.apache.openejb.cdi.CdiResourceInjectionService.fillInjectionProperties(CdiResourceInjectionService.java:170)
	at org.apache.openejb.cdi.CdiResourceInjectionService.injectJavaEEResources(CdiResourceInjectionService.java:130)
	at org.apache.webbeans.portable.InjectionTargetImpl.injectResources(InjectionTargetImpl.java:278)
	at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:209)
	at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:205)
	at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:196)
	at org.apache.webbeans.component.AbstractOwbBean.create(AbstractOwbBean.java:126)
	at org.apache.webbeans.component.ManagedBean.create(ManagedBean.java:67)
	at org.apache.webbeans.context.DependentContext.getInstance(DependentContext.java:68)
	at org.apache.webbeans.context.AbstractContext.get(AbstractContext.java:125)
	at org.apache.webbeans.container.BeanManagerImpl.getReference(BeanManagerImpl.java:799)
	at org.apache.openejb.server.cxf.rs.CdiResourceProvider$PseudoScopedCdiBeanCreator.create(CdiResourceProvider.java:286)
	at org.apache.openejb.server.cxf.rs.CdiResourceProvider.getInstance(CdiResourceProvider.java:173)
	at org.apache.cxf.jaxrs.JAXRSInvoker.getServiceObject(JAXRSInvoker.java:393)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:98)
	at org.apache.openejb.server.cxf.rs.AutoJAXRSInvoker.invoke(AutoJAXRSInvoker.java:68)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.openejb.server.cxf.rs.CxfRsHttpListener.doInvoke(CxfRsHttpListener.java:253)
	at org.apache.tomee.webservices.CXFJAXRSFilter.doFilter(CXFJAXRSFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by derekm** [comment]
@bcluap -- This change could break existing swagger-jaxrs2 integrations in CDI-enabled environments. Single-coordinate Swagger integrations should be able to simplify themselves with this change, most likely by deleting wrapper objects or support code.

**Comment by derekm** [comment]
@pjfanning & @frantuma -- Swagger 2.0.0-rc4 release notes should indicate that `swagger-jaxrs2` is now CDI-enabled with a `bean-discovery-mode="all"` CDI 2.0 beans.xml. System integrators & early adopters will need to simplify their pre-rc4 Swagger integrations to accommodate this change.

I'm not sure how to mark this on a milestone somewhere so that the release note is sure to be created.

Thanks!

**Comment by derekm** [comment]
PS: I commented on this breakage in the corresponding Issue and recommended against breaking Swagger 1.5's `swagger-jersey2-jaxrs`: https://github.com/swagger-api/swagger-core/issues/2617#issuecomment-358414376

**Comment by derekm** [comment]
I believe this feature went out with 2.0.0-rc4, @frantuma. Here is me exercising it in Hammock: https://github.com/hammock-project/hammock/pull/125/files

**Comment by irvinhg** [comment]
@bcluap getting the same problem, did you find out why ?

**Comment by bcluap** [comment]
Hi Irvin,

I worked around it by telling the CDI implementation (openejb in TomEE) to
ignore the swagger package by
passing: -Dopenejb.additional.exclude=swagger-jaxrs

Paul Carter-Brown
Director
Jini Guru
m: +27 (0) 83 442 7179 <+27834427179>
a: Golfers Building, Design Quarter, Cnr William Nicol and Leslie
  Johannesburg, South Africa
w: jini.guru  e: paul@jini.guru

Disclaimer: This message and/or attachment(s) may contain
privileged, confidential and/or personal information. If you are not the
intended recipient you may not disclose or distribute any of
the information contained within this message. In such case you must
destroy this message and inform the sender of the error. Jini Guru may not
accept liability for any errors, omissions, information and viruses
contained in the transmission of this message. Any opinions, conclusions
and other information contained within this message not related to Jini
Guru official business is deemed to be that of the individual only and is
not endorsed by Jini Guru.

**Comment by irvinhg** [comment]
@bcluap Thanks , the same worked for me.

**Pull request merged**
