### PR TITLE
fix path building for resources without leading slashes

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
also re-factored repetitive code in ReaderUtils.getPath() into a private method

### CODE REVIEW

**Comment by radai-rosenblatt** [comment]
it seems all the various test resources in the code trip jersey validation:
```
[[FATAL] A sub-resource model, public io.swagger.v3.jaxrs2.resources.TestSubResource io.swagger.v3.jaxrs2.resources.TestResource.getEvenMoreSubResource(io.swagger.v3.jaxrs2.resources.model.Pet), can not have an entity parameter. Try to move the parameter to the corresponding resource method.; source='ResourceMethod{httpMethod=null, consumedTypes=[], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class io.swagger.v3.jaxrs2.resources.TestResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@41b7f721]}, definitionMethod=public io.swagger.v3.jaxrs2.resources.TestSubResource io.swagger.v3.jaxrs2.resources.TestResource.getEvenMoreSubResource(io.swagger.v3.jaxrs2.resources.model.Pet), parameters=[Parameter [type=class io.swagger.v3.jaxrs2.resources.model.Pet, source=null, defaultValue=null]], responseType=class io.swagger.v3.jaxrs2.resources.TestSubResource}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.it.resources.MultiPartFileResource.uploadFile(java.lang.String,java.io.InputStream) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[multipart/form-data], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class io.swagger.v3.jaxrs2.it.resources.MultiPartFileResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@2d9ad727]}, definitionMethod=public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.it.resources.MultiPartFileResource.uploadFile(java.lang.String,java.io.InputStream), parameters=[Parameter [type=class java.lang.String, source=fileIdRenamed, defaultValue=null], Parameter [type=class java.io.InputStream, source=fileRenamed, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}', [HINT] A HTTP GET method, public void io.swagger.v3.jaxrs2.petstore.security.SecurityResource.getSecurity(), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class io.swagger.v3.jaxrs2.petstore.security.SecurityResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@5725945]}, definitionMethod=public void io.swagger.v3.jaxrs2.petstore.security.SecurityResource.getSecurity(), parameters=[], responseType=void}, nameBindings=[]}', [HINT] A HTTP GET method, public void org.my.project.resources.ResourceInPackageB.getTest(java.util.ArrayList), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class org.my.project.resources.ResourceInPackageB, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@691ee7f3]}, definitionMethod=public void org.my.project.resources.ResourceInPackageB.getTest(java.util.ArrayList), parameters=[Parameter [type=class java.util.ArrayList, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [HINT] A HTTP GET method, public void com.my.project.resources.ResourceInPackageA.getTest(java.util.ArrayList), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.my.project.resources.ResourceInPackageA, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@176e1b0e]}, definitionMethod=public void com.my.project.resources.ResourceInPackageA.getTest(java.util.ArrayList), parameters=[Parameter [type=class java.util.ArrayList, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public abstract javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.Ticket2644AnnotatedInterface.getResource() and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.Ticket2644ConcreteImplementation.getResource() at matching regular expression /resources. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@6c36d52b', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.HiddenUserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.HiddenAnnotatedUserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) at matching regular expression /user. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@7b191199', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.HiddenUserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.UserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) at matching regular expression /user. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@7b191199', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.HiddenAnnotatedUserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.UserResource.createUser(io.swagger.v3.jaxrs2.resources.model.User) at matching regular expression /user. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@7b191199', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public java.lang.String io.swagger.v3.jaxrs2.resources.TestResource.getStatus() and public java.lang.String io.swagger.v3.jaxrs2.resources.UserAnnotationResource.getStatus() at matching regular expression /status. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@65a65076', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method PUT and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.updatePet(io.swagger.v3.jaxrs2.resources.model.Pet) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.updatePet(io.swagger.v3.jaxrs2.resources.model.Pet) at matching regular expression /pet. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@27781a7', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.addPet(io.swagger.v3.jaxrs2.resources.model.Pet) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.addPet(io.swagger.v3.jaxrs2.resources.model.Pet) at matching regular expression /pet. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@27781a7', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.JsonIdentityCyclicResource.test(io.swagger.v3.jaxrs2.resources.model.ModelWithJsonIdentityCyclic) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.JsonIdentityResource.test(io.swagger.v3.jaxrs2.resources.model.ModelWithJsonIdentity) at matching regular expression /pet. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@27781a7', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.addPetByIntegerNoAnnotation(int) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.addPetByIntegerNoAnnotation(int) at matching regular expression /bodyidnoannotation. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@5832934f', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.addPetNoAnnotation(io.swagger.v3.jaxrs2.resources.model.Pet) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.addPetNoAnnotation(io.swagger.v3.jaxrs2.resources.model.Pet) at matching regular expression /bodynoannotation. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@6b94c409', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.findPetsByStatus(java.lang.String,io.swagger.v3.jaxrs2.resources.QueryResultBean) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.findPetsByStatus(java.lang.String,io.swagger.v3.jaxrs2.resources.QueryResultBean) at matching regular expression /findByStatus. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@3ce61ced', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.findPetsByTags(java.lang.String) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.findPetsByTags(java.lang.String) at matching regular expression /findByTags. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@222c86f', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.addPetByInteger(int) and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.addPetByInteger(int) at matching regular expression /bodyid. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@4ec68b8f', [FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.petstore.PetResource.getPetById(java.lang.Long) throws io.swagger.v3.jaxrs2.resources.exception.NotFoundException and public javax.ws.rs.core.Response io.swagger.v3.jaxrs2.resources.PetResource.getPetById(java.lang.Long) throws io.swagger.v3.jaxrs2.resources.exception.NotFoundException at matching regular expression /([^/]+). These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@33fbad2']
```

i dont think this has anything to do with my changes, though

**Comment by radai-rosenblatt** [comment]
i've removed my test application and resource classes as they were causing issues with integration tests.
currently it looks like there's a test vulnerable to definitions order (1/2 tests suceeded) - i've copied the failing test diff for convenience: https://www.diffchecker.com/qMDbzop3

**Comment by andi5** [comment]
Would that fix #2751 ?

**Comment by radai-rosenblatt** [comment]
@andi5 - i think (hope?) so. me running into a similar problem is what triggered this PR

**Comment by frantuma** [comment]
included and replaced by #2758

**Pull request closed without merging**
