### PR TITLE
updated versions for release

### PR DESCRIPTION
**Pull request by fehguy**

### CODE REVIEW

**Comment by jplock** [comment]
Has 1.5.12 been published to maven central?

**Comment by fehguy** [comment]
Yes, release notes published as well

**Comment by jplock** [comment]
Cool thanks.  I just hadn't seen it on http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.swagger%22%20AND%20a%3A%22swagger-core%22 yet

**Comment by fehguy** [comment]
Depends on load to sync from sonatype to maven central

**Pull request merged**
