### PR TITLE
jackson-2.7.8 (with one broken test disabled)

### PR DESCRIPTION
**Pull request by pjfanning**
I tried experimentally to upgrade jackson for https://github.com/swagger-api/swagger-core/issues/1937.
I upgraded joda-time too because jackson has a dependency on a newer version.
I fixed one issue by creating an ObjectNode comparator but there is still one broken test in swagger-jaxrs.

### CODE REVIEW

**Comment by pjfanning** [comment]
@fehguy Would it be possible to have someone look at the PR and the broken test? The recent merge in swagger-scala-module to upgrade Jackson-scala-module will possibly not work without a general Jackson upgrade (@sirrochj). I'm afraid I am travelling for a few weeks, so I'm not in a position to debug the test issue here. 
It seems that to use Jackson 2.8, only joda-time needs a further upgrade.

**Comment by pjfanning** [comment]
I have created a test project that demonstrates the Jackson TypeFactory change that is affecting the GenericsTest - https://github.com/pjfanning/JacksonTest

**Comment by fehguy** [comment]
@pjfanning yes, looks like the behavior has changed with jackson 2.7.8.  I'll see if this magically is fixed by 2.8.x--if not, it's going to be a bear to track down.

**Comment by pjfanning** [comment]
@fehguy the same issue occurs with jackson 2.8.4.

**Comment by pjfanning** [comment]
@fehguy with the recent merges reducing some of the issues with using newer jackson jars, I think it is ok to delay completing this task. I've been able to use a swagger jars based on the latest trunk code with the latest jackson jars. Would it be feasible to release a v1.5.11 in the near future?

**Comment by fehguy** [comment]
@pjfanning yes, I was hoping to get the jackson version updated.  There are some issues in 2.4.x that necessitate an update.  Can you send a PR to get us above 2.5 and I can release today?

**Comment by pjfanning** [comment]
I can add a pull request shortly to upgrade to 2.5.5. I tried 2.6.7 but one test in ModelConverterTest failed (processModelWithPairProperties) - this does not appear to fail with jackson 2.8.4 but the test issue in this pull request happens there (GenericsTest).

**Comment by pjfanning** [comment]
https://github.com/swagger-api/swagger-core/pull/2041

**Comment by pjfanning** [comment]
Superseded by https://github.com/swagger-api/swagger-core/pull/2044

**Pull request closed without merging**
