### PR TITLE
Monetary Amount added as a primitive type

### PR DESCRIPTION
**Pull request by ssoffline**
Monetary Amount added as a primitive type, right now Monetary Amount ends up opening all the internal classes on UI, making it virtually impossible to use.

### CODE REVIEW

**Comment by fehguy** [comment]
Well not if the PR breaks all the tests!  See if you can address the tests and we can look.

**Comment by ssoffline** [comment]
Its major minor version, are you guys on Java 7, seems to be depend on java 8

**Comment by fehguy** [comment]
Yes Java 7. Next version Java 8. It can be done with class names though

**Comment by ssoffline** [comment]
Will give you a java 7 fix

**Comment by ssoffline** [comment]
Build has passed now, after adding java-money-bp

**Comment by ssoffline** [comment]
I need to pull it back, will contribute again, this may lead to certain violations.

**Comment by ssoffline** [comment]
I can check in this fix/feature in from my company portal, are you ready to accept this PR or you guys have different plans to implement this?

**Comment by fehguy** [comment]
I'm confused :)  Would be happy to add the support when builds pass and your company gives you permission to contribute, assuming it follows the framework style and doesn't break things.

**Pull request closed without merging**
