### PR TITLE
add dependabot.yml for dependency management

### PR DESCRIPTION
**Pull request by sullis**
Dependabot version 2:
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### CODE REVIEW

**Comment by sullis** [comment]
LGTM

**Comment by sullis** [comment]
@frantuma

**Comment by sullis** [comment]
WDYT? @frantuma

**Comment by frantuma** [comment]
Sorry about late response, a quick update: we are considering this, but still have doubts about real added value, as tests cannot cover 100% of possible regressions, and careful checks must be applied; this means that PRs will be little more than a "notification" of update existence and not evident breaking, and this could be possibly not so useful noise.

But this doesn't mean we will not apply it, we have it in sight and keep updates here.

**Pull request closed without merging**
