### PR TITLE
Develop 2.0 - support binary input and output

### PR DESCRIPTION
**Pull request by boazsapir**
See my proposed spec https://github.com/swagger-api/swagger-spec/issues/50

These changes in swagger-models are a precondition for an implementation in swagger-codegen of the proposed spec update, as detailed in the above mentioned swagger-spec issue #50, to support binary input and output

### CODE REVIEW

**Comment by boazsapir** [comment]
See also https://github.com/swagger-api/swagger-codegen/pull/868

**Comment by webron** [comment]
We still need to make a decision on that issue before merging this PR.

**Comment by webron** [comment]
@boazsapir - finally clearing out the PRs (as much as I can). Based on our discussion, I imagine this is no longer relevant (that is, it needs to be modified)?

**Comment by boazsapir** [comment]
I agree.
BTW is the new proposal confirmed or are we still waiting for input from more people?

**Comment by webron** [comment]
I believe I talked with Tony about it offline, but let me just make sure :)

**Pull request closed without merging**
