### PR TITLE
Make sure access field is populated when constructing BodyParam obj

### PR DESCRIPTION
**Pull request by colinmccabe**
Make sure the access field in an @ApiParam annotation gets copied to BodyParam.

### CODE REVIEW

**Comment by webron** [comment]
Just curious, have you encountered a related issue?

**Comment by colinmccabe** [comment]
I noticed this when trying to hide parameters with a SpecFilter that looked at the access field, as described here: http://stackoverflow.com/questions/22812365/how-to-hide-a-parameter-in-swagger. The parameter I was trying to hide happened to be BodyParam.

**Comment by webron** [comment]
Fair enough. And one other question, are you trying to hide it completely or really based on some `access` value?

**Comment by colinmccabe** [comment]
I'm trying to remove it completely from the generated swagger.json, with a custom SpecFilter similar to the one in the StackOverflow link above.

My API takes a session param, which Swagger is interpreting as a BodyParam. I'm aiming to hide it declare the session param an ApiImplicitParam instead.

**Comment by webron** [comment]
In that case, be on the lookout for #1188 which would give you the same effect without having to configure a SpecFilter. 

Thanks for the PR!

**Pull request merged**
