### PR TITLE
#1896 Fixed io.swagger.jackson.ModelResolver - Composition model when resolving child type

### PR DESCRIPTION
**Pull request by iblocks-shaun**
Resolves [issue 1896](https://github.com/swagger-api/swagger-core/issues/1896). 

**Issue Summary**
(Please refer to the issue for more details and examples)

When the io.swagger.jackson.ModelResolver's resolve method is called with a parent type, the ModelResolver will create a parent model, as well as a child composition model that references that parent model and does not contain the parent properties. However, when called with a child type, the ModelResolver will create a single model containing both the parent and child properties. 

...details from issue omitted here...

I have updated ModelResolver so that, when presented with the child class as its starting point, the resolve method will define the same set of models in the ModelConverterContext that it would define when presented with the parent class as its starting point. It will still return the child model, but this will be a composition model that references the parent model. The resolve method will only define models for the child class in this manner if three conditions are met. The conditions under which the above will occur include the following:
1.     The child type must have an ApiModel annotation specifying its parent type in the parent property of the annotation.
2.     The child type must in fact be a child of the parent type, as determined by the AnnotationIntrospector instance (_intr) in the parent AbstractModelConverter class.
3.     The ApiModel annotation in the parent class must specify a subTypes property containing the child type.

### CODE REVIEW

**Comment by iblocks-shaun** [comment]
@fehguy Any thoughts regarding this merge request? Apologies for asking, I know you are busy and there are many merge requests to review on this project. We are somewhat reliant on this merge request being accepted to be able to use Swagger Annotations. Likewise for the following merge requests:
- https://github.com/swagger-api/swagger-core/pull/1895

- https://github.com/swagger-api/swagger-core/pull/1905

If it helps, I can create a single merge request that combines all three of these. Again, I apologise for being forward and asking for thoughts.

**Comment by fehguy** [comment]
Hi @iblocks-shaun no problem checking.  I have to make sure this is tested correctly and doesn't break any downstream projects

**Comment by iblocks-shaun** [comment]
Checks are failing on this pull request due a bug in pull request [1959](https://github.com/swagger-api/swagger-core/pull/1959). A correction has been provided in pull request [1991](https://github.com/swagger-api/swagger-core/pull/1991).

**Comment by fehguy** [comment]
replaced by #1991

**Comment by iblocks-shaun** [comment]
@fehguy Pull request [1991](https://github.com/swagger-api/swagger-core/pull/1991)  does not resolve issue [1896](https://github.com/swagger-api/swagger-core/issues/1896). This pull request is intended to resolve that issue. Please can this pull request be re-opened. I will be merging in master to this branch and pushing soon.

**Comment by iblocks-shaun** [comment]
@fehguy I have merged master into the branch involved in this merge request and pushed. Is there any chance this pull request could be re-opened or should I submit a new one, which references this one?

**Comment by fehguy** [comment]
Sure--this PR was failing, I must have misunderstood the relationship between the two.

**Pull request merged**
