### PR TITLE
To be able to use Gradle's Task Configuration Avoidance feature bump Gradle version to `5.6.2`

### PR DESCRIPTION
**Pull request by bronogard**
For more details click on [Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).

### CODE REVIEW

**Comment by bronogard** [comment]
@frantuma please have a look at this PR. thx

**Comment by bronogard** [comment]
@frantuma a friendly reminder to have a look at this PR.
Upcoming PR's of mine are depending on this change. thx

**Comment by joschi** [comment]
@bronogard Thanks for your contribution!

Could you elaborate a little bit on which features you'd want to add to swagger-gradle-plugin based on the Task Configuration Avoidance of Gradle 5.6+?

Is Gradle 5.6.2 the lowest version which supports the necessary features?
I'm just wondering what the baseline we should target for the Gradle plugin.

**Comment by frantuma** [comment]
gradle upgraded to 6.x in #3630

**Pull request closed without merging**
