### PR TITLE
Add vendor extentions to ObjectProperty and MapProperty. [241]

### PR DESCRIPTION
**Pull request by roykachouh**
I hope you don't mind, but I came across this issue:

https://github.com/swagger-api/swagger-spec/issues/241

I ran into a problem after reading the swagger spec, which seems to suggest the abillity to add a vendor x on a object property.

When using the parser, the vendor-x is blank on a map property.

### CODE REVIEW

**Comment by fehguy** [comment]
Hi, in concept it sounds good but you now have a failing test.  Do you want to look at that?

**Comment by fehguy** [comment]
sorry, didn't mean to close

**Comment by roykachouh** [comment]
Oh sorry bout that. It was late last night, will take a look later today.

**Comment by roykachouh** [comment]
Fixed the tests.

**Comment by webron** [comment]
Can you rebase please?

**Comment by webron** [comment]
Also, the test doesn't seem to cover the MapProperty.

**Comment by roykachouh** [comment]
Hi @webron, just rebased.

> Also, the test doesn't seem to cover the MapProperty.

I'm not sure I follow. It looks like it's covering the map property - unless, I'm missing something. If anything, it doesn't seem to be covering the ObjectProperty. I added a test for that, will wait on some clarification on the MapProperty

**Pull request merged**
