### PR TITLE
Feature/getresource encoding

### PR DESCRIPTION
**Pull request by mauhiz**
Apis description show garbled encoding on platforms where default charset is not UTF-8.

This PR fixes this issue by forcing the serialization charset to UTF-8, and declaring it in the returned content-type; it also fixes a variety of questionable or outdated coding practices in this file.

### CODE REVIEW

**Comment by mauhiz** [comment]
Will someone please review this?

**Comment by fehguy** [comment]
Hi, this looks good, and apologies for the delay in the review.  It slipped through the cracks.

The proper develop branch is develop_scala-2.10 for sending the PR.  Can you please point it there and I'll merge?

**Comment by mauhiz** [comment]
@fehguy Thanks! Will do.

What about the scala 2.11 support branch, would my changes be merged into it later?

**Comment by fehguy** [comment]
that is correct.  we use develop_scala-2.10 as the "main" develop branch and I'll merge into 2.11.  It's ugly, I know

**Pull request closed without merging**
