### PR TITLE
added format override

### LINKED ISSUE #469: Requirement: hidden password for APiParam
Not sure currently swagger can support to hidden the password in plaintext.
Currently, we 're using swagger-annotations_2.10. For ApiParam definition, we don't see any field to support hidden param value in plaintext.

### PR DESCRIPTION
**Pull request by fehguy**
Fixes #469

### CODE REVIEW

**Comment by andreas-fey** [comment]
So, how does this fix showing a password in swagger as **** ?

**Comment by fehguy** [comment]
It's part of the solution to let the format be `password`.  Now the front-end can choose to hide the input value

**Comment by fehguy** [comment]
Simply set `type="string", format="password"` and swagger-ui will render the password correctly.

**Comment by andreas-fey** [comment]
Seems that the "format" attribute did it not make into the https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#apimodelproperty , did it?

**Comment by fehguy** [comment]
No, the original issue was around params, not model properties.  Please open a new issue if you're looking at model property support.

**Pull request merged**
