### PR TITLE
Gradle plugin test not working under windows

### PR DESCRIPTION
**Pull request by bronogard**
This fixes compile errors during Gradle plugin test execution under windows

``` ... build file '...\junit4904532710138528800\build.gradle': 3: unexpected char: '\' ...)```

 by normalizing all file paths used in Gradle build script.

### CODE REVIEW

**Comment by bronogard** [comment]
@frantuma could you have a look at this PR. thx

**Comment by bronogard** [comment]
@frantuma a friendly reminder to have a look at this PR. thx

**Comment by bronogard** [comment]
@frantuma I would be great if you could have a look at this PR too. thx

**Comment by frantuma** [comment]
Thanks @bronogard ! (eventually..)

**Pull request merged**
