### PR TITLE
Make Gradle plugin custom task 'ResolveTask' cacheable

### PR DESCRIPTION
**Pull request by bronogard**
Enh: enable caching of Gradle custom task with type 'ResolveTask' - remove compatibility to Gradle versions prior to 3.2

### CODE REVIEW

**Comment by bronogard** [comment]
@frantuma a friendly reminder to have a look at this PR. thx
P.S.
Could you give me some description of how to become an official contribution member?

**Comment by bronogard** [comment]
Do you know whom besides @frantuma could be pinged to have a look at this PR? I am looking forward to have this integrated soon in one of the next releases. thx
P.S.
@webron thanks for the fast response. Is the link to [How to contribute](https://github.com/swagger-api/swagger-core/wiki#how-to-contribute) the guide you are talking about?

**Comment by webron** [comment]
@bronogard another thing to add to the to do list, heh, update the wiki. I was referring to https://github.com/swagger-api/.github/blob/master/CONTRIBUTING.md though.

Right now we're overloaded with requests so it's not that you're being ignored, but rather that we have to prioritize the efforts. And yes, I realize that's where the benefit of adding additional maintainers comes in, which is why we're trying to find the right way to do this, but I have no ETA for it.

**Comment by bronogard** [comment]
@webron thanks for the clarification.
The thought of being somehow ignored certainly crossed my mind. ;(
Could you give me some ETA when I can expect a review of this PR? thx

**Comment by frantuma** [comment]
@bronogard eventually merged #3321 which includes and replaces this PR. Thanks a lot for your contribution!

**Comment by bronogard** [comment]
@webron when do you release a new version in general and what are the criteria (e.g. number of merged PullRequests)? thx

**Comment by webron** [comment]
@bronogard At the moment, we don't have well defined criteria.

**Pull request closed without merging**
