### PR TITLE
Fixing 1201 - array property constraint deserialisation

### PR DESCRIPTION
**Pull request by conorclifford**
Small fix for #1201 (missing deserialisation of ArrayProperty constraints (`minItems`, `maxItems` and `uniqueItems`).

### CODE REVIEW

**Comment by fehguy** [comment]
@frantuma look OK to you?

**Comment by cipresso** [comment]
Hi @fehguy. I have the same issue described in #1201 on both 1.5.8 and 1.5.9.  I need the fix committed by @conorclifford as I'm deserializing JSON schema that has minItems and maxItems and embedding the resultant Model.

**Comment by cipresso** [comment]
Hi.  I tried out the fix and it works.  There's an unnecessary import statement "import com.google.common.collect.Maps;" you might want to remove.

**Comment by webron** [comment]
@cipresso thanks for validating it.

**Comment by brando76** [comment]
I understand that this pull request is the first step to resolving the issue of maxItems within definitions of not being read by swagger-parser (https://github.com/swagger-api/swagger-parser/issues/239).  Just wanted to mention that this issue is currently causing our internal code generator (which uses swagger-parser/swagger-core) to not handle this case.  Whatever could be done to resolve this we would be most grateful for.

**Pull request merged**
