### PR TITLE
classgraph 4.8.86

### PR DESCRIPTION
**Pull request by sullis**
release notes:
https://github.com/classgraph/classgraph/releases

### CODE REVIEW

**Comment by sullis** [comment]
@frantuma

**Comment by sullis** [comment]
LGTM @frantuma

**Comment by joschi** [comment]
@sullis Thanks for your contribution!

Since we are already at it, should we update to the latest stable version?
https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.80

**Comment by sullis** [comment]
latest stable version is classgraph 4.8.83

Ready for review.

**Comment by sullis** [comment]
latest stable version is classgraph 4.8.86

Ready for review.

**Comment by sullis** [comment]
obsolete.

**Pull request closed without merging**
