### PR TITLE
Swagger scans methods on JAX-RS resources not annotated to be Swagger operations

### PR DESCRIPTION
**Pull request by titiu7**
This is related to issue #1343. The fix that was provided allowed Swagger to skip methods without REST annotations which was just one part of the problem. In Swagger-Core v1.5.4, all the methods annotated to be REST service methods are scanned even if they don't have the annotation @ApiOperation. I believe this shouldn't be the case according to the Swagger documentation. 
As an example, let's assume we have the following method in a REST resource class:

```
@GET 
@Path("/")
public String getString() {
 String str = "test method";
return str;
}
```

Swagger will include that method regardless the fact that it's not annotated with @ApiOperation. This pull request addresses that issue.

Thanks

### CODE REVIEW

**Comment by fehguy** [comment]
I don't believe we can merge this, as it fundamentally changes how the processor works.  I'm going to keep it open so documentation can be improved but also ensure it's behaving as intended.

**Comment by titiu7** [comment]
Hey @fehguy, do you think this issue will be addressed anytime soon in the upcoming versions?

**Comment by webron** [comment]
@titiu7 - did you get a chance to test 1.5.8 for that functionality? I know @frantuma has done some work in the field.

**Comment by titiu7** [comment]
@webron thanks for your reply. I tested out 1.5.8, but that functionality is still not there yet. @frantuma, can you share your thoughts on this. Thanks

**Comment by pixels4nickels** [comment]
Is there any workaround for this? Is there any way to exclude packages or something? Servlets using Enterprise Web Objects are invoking this error for me:
`java.lang.IllegalArgumentException: Conflicting setter definitions for property "userInfo": com.webobjects.eocontrol.EOObjectStore#setUserInfo(1 params) vs com.webobjects.eocontrol.EOObjectStore#setUserInfo(1 params)`

**Comment by fehguy** [comment]
We've clarified how the processing picks up annotations, please see here for details:

https://github.com/swagger-api/swagger-core/releases/tag/v1.5.9

**Pull request closed without merging**
