### PR TITLE
Fixes swagger-api/swagger-codegen#980 : Allowing inheritance without additonal properties

### PR DESCRIPTION
**Pull request by maxime-morand**
Fixes swagger-api/swagger-codegen#980

In swagger-codegen, a model which inherit from an other without defining its own properties will result in a NullPointerException. The error is caused by the ModelDeserializer which create a CompoundModel without any parent.
This fix would allow such a case.

### CODE REVIEW

**Comment by webron** [comment]
@maxime-morand - is there a respective ticket opened on swagger-codegen?

**Comment by maxime-morand** [comment]
@webron - no, i did not find any

**Comment by webron** [comment]
@maxime-morand - can you please open one and link to the PR? This is for documentation purposes, especially with a cross-project dependency. Should end up in the release notes of the codegen when it's released with the fix.

**Comment by maxime-morand** [comment]
Fixes Swagger/swagger-codegen#980

**Comment by fehguy** [comment]
Looks good, thanks for contributing.

**Comment by webron** [comment]
Heh, I believe @fehguy meant to merge it ;)

**Comment by maxime-morand** [comment]
@webron thanks a lot, but i think you merged my first commit. There is still a NPE because the child is null (that's what my second commit corrected)

**Comment by webron** [comment]
PR merges works on PRs as a whole, not specific commits. If something was left out, it means the PR wasn't created properly. Feel free to submit an additional PR to cover what's missing.

**Pull request merged**
