### PR TITLE
Fixing polymorphism issues

### PR DESCRIPTION
**Pull request by roni-frantchi**
- Fixed: https://github.com/swagger-api/swagger-core/issues/1737
- Fixed: https://github.com/swagger-api/swagger-core/issues/1740
- Fixed: https://github.com/swagger-api/swagger-core/issues/1549

### CODE REVIEW

**Comment by roni-frantchi** [comment]
@fehguy ?... anyone...?
It's been almost 6 months now... 
Any reason not to merge?.. Any changes that I should make?..

**Comment by webron** [comment]
Hi @roni-frantchi - the biggest reason is time :) We can possibly review this in about two weeks (definitely not this week), but I can't guarantee that. It looks like this PR needs to be resynced with the code before it can be merged.

**Comment by webron** [comment]
Oh, and Shana Tova.

**Comment by roni-frantchi** [comment]
@webron will get right on resolving those pesky conflicts and push for reviewal

Shana Tova :)

**Comment by roni-frantchi** [comment]
@webron @frantuma @fehguy any news on this one?...

**Comment by fehguy** [comment]
I'm sorry for this taking so long, but this introduces attributes which are illegal in the spec (`parent`) so we can't merge it.

**Comment by roni-frantchi** [comment]
@fehguy wait, what?
First, wasn't 'parent' an attribute that was already available?
Second, isn't the spec extendible so that one can add further metadata?
Third, how about a suggestion of what would be a valid approach?

**Comment by fehguy** [comment]
There is a difference between having a property in the java pojo and in the JSON/YAML description.  This:

https://github.com/sapienstech/swagger-core/blob/2e5df42c7053660c8fc34e4e6cb128a9d4e3661b/modules/swagger-core/src/test/resources/Cat.json#L15

Is not valid in the specification:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

And can't be there.  We can have private fields in the pojos, but they cannot live in the JSON generated.

**Comment by roni-frantchi** [comment]
> There is a difference between having a property in the java pojo and in the JSON/YAML description. 
@fehguy that's understood. Looking for recommendation of what fixes I may apply here that would make the approach valid.

**Comment by roni-frantchi** [comment]
@fehguy the spec says:
> While the Swagger Specification tries to accommodate most use cases, additional data can be added to extend the specification at certain points.
>The extensions properties are always prefixed by "x-" and can have any valid JSON format value.

So, if I add that prefix, meaning `parent` would become `x-parent`, that would become a valid approach, right?
Would you like me to open another PR with that change in place?

**Pull request closed without merging**
