### PR TITLE
Support proper mapping of the byte array

### PR DESCRIPTION
**Pull request by reta**
An attempt to properly map `byte[]` to the `ByteArraySchema` or `BinarySchema` depending on the format specified (if any). The idea here is to introduce the support in `PrimitiveType` of types which could be mapped to multiple schemas, depending on the format, with the first one being the default in case format is omitted. Closes https://github.com/swagger-api/swagger-core/issues/3944 and https://github.com/swagger-api/swagger-core/issues/3511.

Specification snippets generated:
```
        bytes:
          type: string
          format: byte
```

```
        binary:
          type: string
          format: binary
```

@webron would really appreciate the feedback if this change make sense, test cases are include, thanks a lot.

### CODE REVIEW

**Comment by reta** [comment]
My apologies @webron , any interest or feedback on this pull request would be much appreciated, thank you :-)

**Comment by martin-tarjanyi** [comment]
@reta, I created a **[pull request](https://github.com/reta/swagger-core/pull/1)** for your branch to add support for base64 encoded string examples for byte and binary format. Please, consider including it. Thanks.

**Comment by reta** [comment]
thanks @martin-tarjanyi , included, hopefully we could get some attention from the team

**Comment by reta** [comment]
@frantuma @HugoMario guys, mind please taking a look? thank you!

**Comment by reta** [comment]
@HugoMario @frantuma hey guys, any chance someone could look at it? thank you!

**Comment by HugoMario** [comment]
hey @reta , sure. I'll take a time this week to check your PR

**Comment by reta** [comment]
hey @HugoMario , any chances to have a pair of eyes on it? :-) Thank you!

**Comment by RKInnovalor** [comment]
@HugoMario did you have a chance to look at this PR yet?

**Comment by HugoMario** [comment]
Hey @reta 
Is the jetty version update related to changs in byte array?
BTW, PR looks good to me. I'll sync up again with my team to check this again.

Sorry for so much delay

**Comment by reta** [comment]
Hey @HugoMario !

> Hey @reta Is the jetty version update related to changs in byte array? 

No, it shouldn't be (AFAIK)

> BTW, PR looks good to me. I'll sync up again with my team to check this again.

Thanks a mill, really appreciate it!

**Comment by frantuma** [comment]
Thanks all for your patience, this is included and replaced by https://github.com/swagger-api/swagger-core/pull/4659

**Comment by RInverid** [comment]
Cool! one question: my current workaround for this issue is to annotate all endpoints returning byte[] as returning byte. Is this change compatible with this workaround? or will I need to pay attention when upgrading to the next version?

thanks a lot

**Pull request closed without merging**
