### PR TITLE
use maven wrapper to ensure maven 3.3.9 is used

### PR DESCRIPTION
**Pull request by pjfanning**
and upgrade maven-jar-plugin to 3.0.2
Based on some issues I ran into when testing on travis-ci.
Using maven wapper is recommended in:
https://github.com/travis-ci/travis-ci/issues/4872

### CODE REVIEW

**Comment by tobilarscheid** [comment]
maven wrapper is awesome!

**Comment by webron** [comment]
@pjfanning Sorry for the delay, and thanks for this. Would you consider submitting a similar PR to the `2.0` branch (our next-get core)?

**Comment by pjfanning** [comment]
@webron I just added https://github.com/swagger-api/swagger-core/pull/2431

**Comment by webron** [comment]
Hmm, some bad news. Even though the PR built properly, master's build is failing after merge.

**Comment by pjfanning** [comment]
@webron I raised a Travis CI bug - https://github.com/travis-ci/travis-ci/issues/8455
There seems to be a problem with builds that use oraclejdk7.
The 2.0 branch uses oraclejdk8 without issue

**Comment by webron** [comment]
Any idea if the issue also exists with openjdk7? We can switch to that. Otherwise, we'll have to revert the PR for now.

**Comment by pjfanning** [comment]
I've kicked off a PR build with openjdk7: https://github.com/swagger-api/swagger-core/pull/2432

**Comment by pjfanning** [comment]
@webron https://github.com/swagger-api/swagger-core/pull/2432 passed - could you merge that?

**Comment by webron** [comment]
Great, we're making progress.

**Pull request merged**
