### PR TITLE
Consider java.time.OffsetDateTime a Swagger DateTime primitive

### PR DESCRIPTION
**Pull request by acourtneybrown**

### CODE REVIEW

**Comment by Hades32** [comment]
@fehguy why hasn't this been merged yet?

**Comment by fehguy** [comment]
Because there's too much to do :)  I don't just merge without testing, and I should get to this shortly.  Perhaps @frantuma can review faster than me.

**Comment by Hades32** [comment]
Good to know, I already feared there might be valid reasons to refuse it. 

It's really strange how the swagger online editor and cli generate Java8 time types, but the swagger UI doesn't properly support it...

**Comment by webron** [comment]
@Hades32 doesn't support it how?

**Comment by Hades32** [comment]
@webron it's not shown as a timestamp but instead a large json object with many fields. so pretty useless...

**Comment by fehguy** [comment]
@webron I don't see why we wouldn't do this--but we do need to add some tests before merging, or it'll get lost.

**Comment by webron** [comment]
All I was asking is how this is seen in swagger-ui as some people expect it to be something other than a string. It definitely shouldn't appear as a multi-field object.

**Comment by danny-zegel-zocdoc** [comment]
@fehguy @webron any ETA on merging this?

**Comment by Helmsdown** [comment]
+1 for this PR

**Comment by Helmsdown** [comment]
@webron This is how it renders...
image

**Comment by Helmsdown** [comment]
@webron @fehguy if it means anything....I vouch for this change it is almost identical to the change I made to support ZonedDateTime. Unfortunately, you can't add tests because the project compiles for java 6 (assuming that has not changed).

https://github.com/swagger-api/swagger-core/pull/1715

**Comment by xunnanxu** [comment]
+1 for this

**Comment by dwhu** [comment]
+1

**Pull request merged**
