### PR TITLE
Update extension properties to support parse value (openAPI)

### PR DESCRIPTION
**Pull request by donaltuohy**
PR to go with issue https://github.com/swagger-api/swagger-core/issues/3375

### CODE REVIEW

**Comment by frantuma** [comment]
This looks nice, thanks a lot! Could you possibly also add a test to the PR?

**Comment by donaltuohy** [comment]
Added tests now @frantuma :)

**Comment by frantuma** [comment]
Thanks!

**Comment by donaltuohy** [comment]
Hey @frantuma any idea when the next version of 1.5 will be released with this change?

**Comment by adampurser-zendesk** [comment]
Any update on this change being released?

**Pull request merged**
