### PR TITLE
Add Property.isPrimitiveType()

### PR DESCRIPTION
**Pull request by garydgregory**
For advanced Swagger model processing, I need a clean way to distinguish primitive types from others. This patch add the method Property.isPrimitiveType() and implements it in primitive property classes.

### CODE REVIEW

**Comment by garydgregory** [comment]
I see that Travis failed the build: https://travis-ci.org/swagger-api/swagger-core/builds/231706519?utm_source=github_status&utm_medium=notification

I am not sure what this failure means or what the Swagger Model way is here. Suggestions?

**Comment by fehguy** [comment]
I'm guessing that the build won't work on your local machine either--there are numerous test failures due to changes in signatures, probably making the JSON schema invalid.  I'd suggest looking at them locally to see what the cause is.

**Comment by garydgregory** [comment]
I am going to revisit this convenience method later. I will create a new PR with a narrower footprint to achieve the same goal with a new method PrimitiveType.isSwaggerPrimitive(Property).

**Comment by fehguy** [comment]
Closing per #2206

**Pull request closed without merging**
