### PR TITLE
added empty string check

### LINKED ISSUE #1568: not using default values causes stacktrace for integers
please see: https://github.com/springfox/springfox/issues/1100 as a reference

```
 WARN 2015-12-15 07:51:28,834 [tomcat-http--46][] io.swagger.models.parameters.AbstractSerializableParameter - Illegal DefaultValue  for parameter type integer
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:453)
    at java.lang.Long.valueOf(Long.java:540)
    at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:161)
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.get(BeanPropertyWriter.java:726)
```

### PR DESCRIPTION
**Pull request by fehguy**
fixed #1568

### CODE REVIEW

**Comment by fehguy** [comment]
@garydgregory 1.5.6 was just release to maven central, and includes this fix

**Comment by raoravik** [comment]
@Golenko Was this picked up for springfox? I am still getting the same error with springfox 2.3.1

**Comment by Golenko** [comment]
@raoravik I believe it wasn't :(
I gave it a single try about a month ago and I was getting the same error too..

**Comment by webron** [comment]
@dilipkrish - can you take a look at this please?

**Pull request merged**
