### PR TITLE
make swagger-jersey2-jaxrs OSGi friendly

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by maggu2810** [comment]
Handle the jersey2-jaxrs jar similar to the other ones that already brings OSGi support.

**Comment by webron** [comment]
@elakito - can you have a look at this please?

**Comment by elakito** [comment]
@webron i'll look at it today.

**Comment by elakito** [comment]
@webron it looks okay. 

One remark that I can make is that the existing two jersey components swagger-jersey-jaxrs and swagger-jersey2-jaxrs are not inherently osgi friendly as they contain the same public packages io.swagger.jersey classes. But assuming only this jersey2 one is becoming an osgi bundle and the other one is not, there will be no conflict.

**Comment by maggu2810** [comment]
Hi @webron, @elakito do you see any change to get this merged in front of the next release?

**Comment by webron** [comment]
@maggu2810 - can you rebase?

**Comment by maggu2810** [comment]
done

**Pull request merged**
