### PR TITLE
Fixed duplicate operation id when using inheritance

### PR DESCRIPTION
**Pull request by HugoMario**
this PR has been created in order to fix to #1939

### CODE REVIEW

**Comment by iblocks-shaun** [comment]
@fehguy This pull request breaks io.swagger.jaxrs.Reader when parsing methods on interfaces. Please see the code block starting at line 764 from this class below:
```
String operationId = null;
// check if it's an inherited method.
if(ReflectionUtils.findMethod(method, cls.getSuperclass()) == null) {
   operationId = method.getName();
} else {
   operationId = this.getOperationId(method.getName());
}
```
Referring in particular `ReflectionUtils.findMethod(method, cls.getSuperclass())` above, cls.getSuperclass() will return null for an interface. `ReflectionUtils.findMethod` does not expect this parameter to be null and throws a NullPointerException when attempting to access the methods on this Class parameter.

**Comment by iblocks-shaun** [comment]
@fehguy OK, I have investigated the issue and this pull request breaks io.swagger.jaxrs.Reader when parsing methods on interfaces. The commit that introduced the bug was 7878cfde405042465dcf3e65135e77ff34b40275. Please see the code block starting at line 764 from this class below:
```
String operationId = null;
// check if it's an inherited method.
if(ReflectionUtils.findMethod(method, cls.getSuperclass()) == null) {
   operationId = method.getName();
} else {
   operationId = this.getOperationId(method.getName());
}
```
Referring in particular `ReflectionUtils.findMethod(method, cls.getSuperclass())` above, `cls.getSuperclass()` will return null for an interface. `ReflectionUtils.findMethod` does not expect this parameter to be null and throws a `NullPointerException` when attempting to access the methods on this Class parameter.

**Comment by fehguy** [comment]
@iblocks-shaun can you please supply a test case?

**Comment by iblocks-shaun** [comment]
Sure. Please see the classes below:
```
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

@Api
@Path("/childType")
public interface TestResource {

    @GET
    @Path("/testValue")
    @ApiOperation("Returns a test value")
    @ApiResponses({@ApiResponse(code = 200, message = "Success", response = String.class)})
    Response getTestValue();
}
```
```
import io.swagger.jaxrs.Reader;
import io.swagger.models.Swagger;

public class TestReaderRunner {
    public static void main(String[] args) {
        new Reader(new Swagger()).read(TestResource.class);
    }
}
```

Fails with the following NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.util.ReflectionUtils.findMethod(ReflectionUtils.java:105)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:765)
	at io.swagger.jaxrs.Reader.read(Reader.java:297)
	at io.swagger.jaxrs.Reader.read(Reader.java:173)
	at TestReaderRunner.main(TestReaderRunner.java:18)
```

**Comment by iblocks-shaun** [comment]
@fehguy The behaviour of the fix in this pull request is also non-deterministic, and depends on whether the child or parent resource class is processed first. Consider the JAX-RS resource classes where TestChildResource inherits from TestParentResource:
```
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

@Api
@Path("/classParent")
public class TestParentResource {

    @GET
    @Path("/testValue")
    @ApiOperation("Returns a test value")
    @ApiResponses({@ApiResponse(code = 200, message = "Success", response = String.class)})
    public Response getTestValue() {
        return Response.ok("Success").build();
    }
}
```
```
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

@Api
@Path("/classChild")
public class TestChildResource extends TestParentResource {

    @GET
    @Path("/testValue")
    @ApiOperation("Returns a test value")
    @ApiResponses({@ApiResponse(code = 200, message = "Success", response = String.class)})
    public Response getTestValue() {
        return Response.ok("Success").build();
    }
}
```
The simple runner below passes a sorted set containing the two resource classes to  `io.swagger.jaxrs.Reader.read(Set<Class<?>> classes)`. In the first instance, the set is sorted so that the child resource is processed first. In the second instance, the set is sorted so that the parent resource is processed first. 
```
import io.swagger.jaxrs.Reader;
import io.swagger.models.Operation;
import io.swagger.models.Path;
import io.swagger.models.Swagger;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

public class SimpleReaderRunner {
    public static void main(String[] args) {
        System.out.println("---TestChildResource class processed before TestParentResource class---");
        Set<Class<?>> testClasses = new TreeSet<Class<?>>(new Comparator<Class<?>>() {
            @Override
            public int compare(Class<?> o1, Class<?> o2) {
                return o1.equals(TestChildResource.class) ? -1 : 1;
            }
        });
        printOperationIds(testClasses);

        System.out.println("---TestParentResource class processed before TestChildResource class---");
        testClasses = new TreeSet<Class<?>>(new Comparator<Class<?>>() {
            @Override
            public int compare(Class<?> o1, Class<?> o2) {
                return o1.equals(TestChildResource.class) ? 1 : -1;
            }
        });
        printOperationIds(testClasses);
    }

    private static void printOperationIds(Set<Class<?>> testClasses) {
        List<Class<?>> testClassesList = Arrays.asList(new Class<?>[]{TestChildResource.class, TestParentResource.class});

        testClasses.addAll(testClassesList);
        Swagger swagger = new Swagger();
        new Reader(swagger).read(testClasses);
        List<String> operationIds = new ArrayList<String>();
        for (Path path : swagger.getPaths().values()) {
            for (Operation operation : path.getOperations()) {
                operationIds.add(operation.getOperationId());
            }
        }
        Collections.sort(operationIds);
        System.out.println(operationIds);

    }

}
```
The printed results from the runner (included below) indicate that the fix only works if the parent resource is processed first. As there is no guarantee that a sorted set will be passed `io.swagger.jaxrs.Reader.read(Set<Class<?>> classes)`, the Reader's behaviour is non-deterministic.
```
---TestChildResource class processed before TestParentResource class---
[getTestValue, getTestValue]
---TestParentResource class processed before TestChildResource class---
[getTestValue, getTestValue_1]
```

**Comment by iblocks-shaun** [comment]
I have implemented a pull request to handle interfaces correctly and to deal with the non-deterministic nature of the original pull request.

**Comment by iblocks-shaun** [comment]
@fehguy Any thoughts on the issues I raised above or the pull request?

**Comment by fehguy** [comment]
Hi @iblocks-shaun sorry for the delay.  I'll be getting to this shortly, been under water for a while and unable to commit the time to review.

**Comment by iblocks-shaun** [comment]
No problem.

**Comment by jpc4242** [comment]
Am I right assuming that that the fix only solves the "operationId collision due to inheritance" if the operationId came from the method name, but the collisions will still be there if I set the operationId by using  "nickname"?

**Pull request merged**
