### PR TITLE
#1319 Error log when dataType is "file" in @ApiImplicitParam (swagger-jaxrs)

### PR DESCRIPTION
**Pull request by msiemczyk**
added file as a primitive type

### CODE REVIEW

**Comment by msiemczyk** [comment]
Can this be merged and released in 1.5.11 please? We have some continuous integration tests that are now failing because this bug is logging an error in our logs.

**Comment by dklotz** [comment]
maybe ping @fehguy will help? this is intended as a fix for #1319, which was erroneously closed

**Comment by msiemczyk** [comment]
@dklotz Thanks, I emailed him.

**Comment by fehguy** [comment]
@msiemczyk @dklotz sorry for the lag.  Yes, this should be fine.

**Pull request merged**
