### PR TITLE
Refs #1106, #1629, #1617, #1614 - JAX-RS Root and Subresources identification, scanning and reading

### PR DESCRIPTION
**Pull request by frantuma**
@fehguy Refs #1106, #1629, #1617, #1614

As discussed, changes JAX-RS root and subresources identification, scanning and reading to be compliant with JAX-RS specs: Root resources are identified by @Path annotation at class level, and sub resources are identified by @Path annotation at method level, along with no @HttpMethod annotation.

It integrates changes from #1617, changing BeanConfig scanning to only consider @Path annotations, and #1629, used as base for further implementation.

Classes not annotated with @Path are only read in case config.scanAllResources is true, maintaining anyway @Api.hidden processing (@Api.hidden classes are never processed).

Tests have been adapted by setting always scanAllResources = true to be able to handle current test root resources classes which are not always annotated with @Path. A further enhancement would be comprehensively adjusting current test resources/classes to fully adhere to JAX-RS specs, possibly in scope of a different ticket.

Code has been tested via project tests and running swagger-samples projects.

### CODE REVIEW

**Comment by fehguy** [comment]
@Helmsdown can you please comment if this addresses your use case?

**Comment by Helmsdown** [comment]
@fehguy I think it will. When a snapshot is built and deployed let me know so I can give it a spin.

**Comment by fehguy** [comment]
So you want me to merge, push, then undo if you don't like it?

**Comment by Helmsdown** [comment]
Well if you are offering. :-)

**Comment by frantuma** [comment]
@mtraynham @fehguy

I am not sure to get exactly what you mean by *duplicates the function in swagger-ui (under it's own API section and it's parents)*; 
I guess you refer to tags, but here behaviour haven't changed if I am not mistaken; it basically adds parent tags to operation only if existing, can you detail what you mean?

Actually I had some additional thoughts about the overall issue, basically root and child JAX-RS resources identification; the scenarios below should include possible options, in acending order of "Jax-rs compliance", eventually IMO option 5. would be the best, but all but Option 1. involve change in behaviour, which I am not sure if it is ok in same minor version, etc. 

Please let me know what you think

In regards to subresource identification,  in scenario 1. subresources are considered when any method, even not annotated with @Path returned a class with @Api; in all other scenarios subresources are only considered when method annotated with @Path and not annotated with any @HttpMethod, regardless of scanAllResources.

**1. PREVIOUS BEHAVIOUR**

reads also root resources if not annotated with @Path. if not annotated with @Path and not with @Api also it reads if isScanAllResources is true

|@Api|reads|
|@Path|doesn't read|
|scanAllResources|reads|
|@Api hidden|doesn't read|
|@Api @Path hidden|doesn't read|
|@Api hidden scanAllResources|doesn't read|
|@Api scanAllResources|reads|
|@Api @Path|reads|
|@Api hidden scanAllResources|doesn't read|
|@Path scanAllResources|reads|
|subresource|doesn't read|
|@Api subresource|reads|

**2.CURRENT BEHAVIOUR WITHOUT FIX ON SUBRESOURCE** (if (readable || (api == null && config.isScanAllResources()) || isSubresource) {

Current PR https://github.com/swagger-api/swagger-core/pull/1636

reads root resources only if annotated with @Path. if not annotated with @Path and not with @Api also it reads if isScanAllResources is true


|@Api|**doesn't read**|
|@Path|doesn't read|
|scanAllResources|reads|
|@Api hidden|doesn't read|
|@Api @Path hidden|doesn't read|
|@Api hidden scanAllResources|doesn't read|
|@Api scanAllResources|reads|
|@Api @Path|reads|
|@Api hidden scanAllResources|doesn't read|
|@Path scanAllResources|reads|
|subresource|doesn't read|
|@Api subresource|reads|

**3.CURRENT BEHAVIOUR WITH FIX ON SUBRESOURCE** (if (readable || (`api == null && config.isScanAllResources()) || isSubresource)`)

Current PR https://github.com/swagger-api/swagger-core/pull/1636 with change to be applied
Same as 2. but resources are always read.


|@Api|**doesn't read**|
|@Path|doesn't read|
|scanAllResources|reads|
|@Api hidden|doesn't read|
|@Api @Path hidden|doesn't read|
|@Api hidden scanAllResources|doesn't read|
|@Api scanAllResources|reads|
|@Api @Path|reads|
|@Api hidden scanAllResources|doesn't read|
|@Path scanAllResources|reads|
|subresource|**reads**|
|@Api subresource|reads|

**4.MORE JAX-RS COMPLIANT BEHAVIOUR**

Code at https://github.com/frantuma/swagger-core/tree/issue-1614-enhanced/
reads root resources only if annotated with (@Path and @Api) or (@Path and scanAllResources). if not annotated with @Path classes are never read.

|@Api|doesn't read|
|@Path|doesn't read|
|scanAllResources|**doesn't read**|
|@Api hidden|doesn't read|
|@Api @Path hidden|doesn't read|
|@Api hidden scanAllResources|doesn't read|
|@Api scanAllResources|**doesn't read**|
|@Api @Path|reads|
|@Api hidden scanAllResources|doesn't read|
|@Path scanAllResources|reads|
|subresource|reads|
|@Api subresource|reads|


**5.FULLY JAX-RS COMPLIANT BEHAVIOUR**

Code to be updated at https://github.com/frantuma/swagger-core/tree/issue-1614-enhanced/

|@Api|doesn't read|
|@Path|**reads**|
|scanAllResources|**reads**|
|@Api hidden|doesn't read|
|@Api @Path hidden|doesn't read|
|@Api hidden scanAllResources|doesn't read|
|@Api scanAllResources|doesn't read|
|@Api @Path|reads|
|@Api hidden scanAllResources|doesn't read|
|@Path scanAllResources|reads|
|subresource|reads|
|@Api subresource|reads|

**Comment by mtraynham** [comment]
@frantuma 
As long as the subresource `@Api` annotation doesn't actually have a `value` set then it works as you intended because no [tags were extracted](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L215) on the subresource.  When I raised the question yesterday, I thought it would generate an empty `Tag`, but that's not the case.

This does leave room for user error though, when we could just skip `Tag` generation for subResources.  For instance, in the case I did set a `value` on the `@Api` annotation for a subresource, the operation would get two `Tag`s.  Albeit, it's a pretty minor issue, I just mistook the code path as *always* generating a `Tag` for the subresource.
```
@Path("/pets")
@Api("Operations on Pets")
public class Pets {
    public Pets() {
    }

    @GET
    public List<String> getAll() {
        return new ArrayList<>();
    }

    @Path("/{id}")
    public Pet get(@PathParam("id") String id) {
        return new Pet(id);
    }

    @Api("Operations on Pet")
    public static class Pet {
        private final String id;

        public Pet(String id) {
            this.id = id;
        }

        @GET
        public String get() {
            return this.id;
        }
    }
}
```
screenshot from 2016-01-28 11 31 26

**Comment by fehguy** [comment]
@frantuma thank you for the detailed response.  I certainly prefer to be fully JaxRS compliant in our solution.  I do believe this will cause some breakage to users though so the impact of this change should be well documented and covered in the release notes.  It has been our intent to follow JAXRS for this feature.

@mtraynham regarding tags, the behavior in the code is to extract them when they're not explicitly set.  So the best way to "avoid user error" is to programmatically configure the tags like such:

```
@Api(value = "/pet", tags = {"pets", "animals"})
```

**Pull request merged**
