### PR TITLE
classgraph 4.8.64

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by creekorful** [comment]
I think this should be merged as soon as possible since it fix a important memory leak: (see https://github.com/classgraph/classgraph/issues/376)

**Comment by frantuma** [comment]
Thanks! included and replaced by #3458 (classgraph 4.8.65)

**Comment by creekorful** [comment]
@frantuma Thanks! Do you have any idea about the next version release date?

**Comment by frantuma** [comment]
No fixed ETA, probably within mid next month

**Pull request merged**
